name: orca4bikes Bot Tests
on:
  push:
    branches:
      - features
      - unit-tests
  pull_request:
    branches:
      - features
      - unit-tests

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test unit tests
        run:  |
          python telebot_test.py
          python userbot_test.py